-- RBAC schema: converted from db/changelog/001-create-role-tables.xml

CREATE TABLE fhir_roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    description VARCHAR(500),
    built_in    BOOLEAN                  NOT NULL DEFAULT FALSE,
    smart_context VARCHAR(20),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_fhir_roles_name UNIQUE (name)
);

CREATE INDEX idx_fhir_roles_name ON fhir_roles (name);

CREATE TABLE fhir_role_scopes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id      BIGINT       NOT NULL,
    scope_string VARCHAR(200) NOT NULL,
    description  VARCHAR(500),
    CONSTRAINT fk_role_scope_role    FOREIGN KEY (role_id) REFERENCES fhir_roles(id),
    CONSTRAINT uq_role_scope         UNIQUE (role_id, scope_string)
);

CREATE INDEX idx_role_scopes_role_id ON fhir_role_scopes (role_id);

CREATE TABLE fhir_user_role_assignments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject     VARCHAR(255)             NOT NULL,
    role_id     BIGINT                   NOT NULL,
    assigned_by VARCHAR(255)             NOT NULL,
    assigned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at  TIMESTAMP WITH TIME ZONE,
    active      BOOLEAN                  NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_user_role_role        FOREIGN KEY (role_id) REFERENCES fhir_roles(id),
    CONSTRAINT uq_user_role_assignment  UNIQUE (subject, role_id)
);

CREATE INDEX idx_user_role_subject ON fhir_user_role_assignments (subject);
CREATE INDEX idx_user_role_active  ON fhir_user_role_assignments (subject, active);
